'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VB.Compiler.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property context() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("context", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_APP() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_APP", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_BluieFolder() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_BluieFolder", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_Box() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_Box", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_COM() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_COM", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_Controls() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_Controls", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_DATA() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_DATA", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_DIR() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_DIR", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_ENV() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_ENV", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_ENV_I() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_ENV_I", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_File() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_File", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_Folder() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_Folder", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_GreyFolder() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_GreyFolder", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_NAV() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_NAV", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_NET() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_NET", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_OrangeFolder() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_OrangeFolder", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_Preferences() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_Preferences", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_Printing() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_Printing", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_PurpleFolder() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_PurpleFolder", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_RED_FOLDER() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_RED_FOLDER", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_Startup() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_Startup", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_SysExt() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_SysExt", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_WEB() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_WEB", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_Write() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_Write", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property LCARS_ICON_YellowFolder() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("LCARS_ICON_YellowFolder", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
